install CAF(ignoring NO_PUBKEY error), install build-essential dependency
prasadtalasila/BITS-Darshini pull request #118
Opened 2017-10-03 11:38 UTC by adityaketkar

…ency for nodejs

2017-10-03 13:55 UTC, prasadtalasila reviewed
Please spin up a vagrant machine, run tool-install.sh and then run the following commands.    
```shell
> cd BITS-Darshini/data/packet
> /usr/bin/time bro -r packet_data.pcap
```

Do post the results of the command.

2017-10-05 06:03 UTC, adityaketkar commented
The terminal shows this:

0.14user 0.01system 0:00.26elapsed 61%CPU (0avgtext+0avgdata 45320maxresident)k
240inputs+72outputs (1major+8296minor)pagefaults 0swaps

2017-10-05 13:17 UTC, prasadtalasila commented
The tomcat7 throws a visible error, but gets installed successfully on vagrant. All vagrant setups are supposed to be clean startup. That's why the repeated java8 installations.

With the proposed tool-install.sh, only the source files of bro gets copied. The binaries do not exist.    

On the machine you are trying, you may be using the bro that got installed using apt-get. You need to check in the context of vagrant for a confirmation. Let me see if there is an easier way to do this and I will get back to you.

2017-10-06 19:42 UTC, prasadtalasila requested changes
please make the suggested changes.

2017-10-06 19:42 UTC, prasadtalasila commented on scripts/tool-install.sh
> +sudo apt-get install -y caf
working command here is:
```shell
sudo apt-get install -y caf --allow-unauthenticated
```

2017-10-06 19:42 UTC, prasadtalasila commented on scripts/tool-install.sh
> +sudo wget https://www.bro.org/downloads/bro-2.5.1.tar.gz
The installation commands given below do not install bro tool. Please see the [installation steps](https://www.digitalocean.com/community/tutorials/how-to-install-bro-on-ubuntu-16-04) and add the commands, url reference at the end of the script as comment.

2017-10-07 12:19 UTC, adityaketkar commented
I did the requested changes and redeployed the analyzer, but now it gives blank screen as shown.

![image](https://user-images.githubusercontent.com/22611315/31307733-ae4edf7a-ab87-11e7-9a3c-3d5db9fb10bf.png)

2017-10-07 12:30 UTC, prasadtalasila commented
Are you logged into the cyberoam? I think there are a few css and js libraries that are pulled from WWW. Please check this again.

2017-10-07 13:22 UTC, adityaketkar commented
Rebuilding the application solved the issue. But populate table is still giving no output when I followed along the  [Usage Tutorial](https://github.com/prasadtalasila/BITS-Darshini/wiki/Usage-Tutorial).

![image](https://user-images.githubusercontent.com/22611315/31308230-aa3637ea-ab90-11e7-87f6-fd55fe011ff9.png)

2017-10-08 02:33 UTC, prasadtalasila commented
The changes proposed in this PR have been indirectly merged in the commit 315de3a. Closing this PR now.

2017-10-08 02:33 UTC, closed without merging

2017-10-08 02:34 UTC, prasadtalasila commented
Thanks @adityaketkar for the work.