javadocs for utils
prasadtalasila/BITS-Darshini pull request #130
Opened 2017-10-24 02:02 UTC by shilparaaju

2017-10-24 12:15 UTC, prasadtalasila requested changes
@shilparaaju 
Please don't add the javadoc to the code base. You can write a shell script that would generate the documentation and stores the same in docs/ folder. The script can be named as __gen_doc.sh__ and placed in __scripts/__ directory.

Right now, the script is not considering the package structure of in.ac.bits.protocolanalyzer.util package. You can use the following command to create javadoc with proper package structure.
```bash
$javadoc -version -author -private -d docs -classpath "<lib-path>/*" -sourcepath . -subpackages .
```
You should also create a package-info.java for util package.

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/Security.java
> + * This utility class is used to provide security.
The class contains wrapper functions around cryptographic algorithms.

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/Security.java
> + * @author Shilpa Raju
Please add the name of __crygnus (Mihir Kakrambe)__ as one of the authors to all the files.

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/ByteOperator.java
> + * This utility allows for various byte operations.
The class contains utility methods for converting byte range into chosen primitive data types (int, short, long etc.).

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/BitOperator.java
> +     * Converts the given byte to an integer array.
please provide an example here.

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/BitOperator.java
> +     * @param b This is the byte from which values are obtained
a summary description of the method is missing here.

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/BitOperator.java
> -     * @throws ArrayIndexOutOfBoundsException
a summary description of the method is missing here.

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/BitOperator.java
> +
This method takes a byte array and produces a smaller byte array indicated by the arguments. If the operation of the method is not clear, please write a skeletal example using the same class. That should make the operation of this method very obvious.

2017-10-24 12:15 UTC, prasadtalasila commented on src/main/java/in/ac/bits/protocolanalyzer/utils/BitOperator.java
> +
Please follow this advice of constructing minimum working example (MWE) for all the methods that are not clear.

2017-11-15 20:25 UTC, shilparaaju commented
@prasadtalasila I have made the changes requested. Please let me know if there is anything else I have to change.

2017-11-17 06:25 UTC, prasadtalasila commented
@shilparaaju The following points still need improvement.

1. As per the pending comments, a few methods still have their description missing.
1. The package-info.java requires some introduction to overall utility of the package.
1. The Javadoc html files need to be removed from the code base.

2017-11-17 19:33 UTC, shilparaaju commented
@prasadtalasila 
I have made the changes. Please let me know if I missed out on anything.

2017-11-18 02:40 UTC, prasadtalasila requested changes
@shilparaaju please make the suggested changes.

@raghavagrawal please read through the javadoc put in this commit and make comments if any of it is not clear to you. If everything is okay, then you can comment with okay status.

2017-11-18 02:40 UTC, prasadtalasila commented on scripts/gen_doc.sh
> +javadoc -version -author -private -d docs -classpath /home/ubuntu/darshini/src/main/java/in/ac/bits/protocolanalyzer/utils/* -sourcepath . -subpackages .
it is better to specify this as a relative path to the location of the script.

2017-11-18 07:47 UTC, shilparaaju commented
@prasadtalasila I made the change requested

2017-11-19 16:52 UTC, merged