Tomcat8
prasadtalasila/BITS-Darshini pull request #150
Opened 2018-01-10 15:22 UTC by raghavagrawal

Server link has been updated, rest all is working as expected.

2018-01-10 17:05 UTC, prasadtalasila commented
@parv and @kapilkalra04 please verify the installation setup by cloning tomcat8 branch of @raghavagrawal and installing on a clean virtual machine. If one of you can do a screen grab of the installation process inside VM, that would serve as help guide for new users.

2018-01-13 02:08 UTC, prasadtalasila commented
@parv and @kapilkalra04 any updates on this PR?

2018-01-13 06:09 UTC, kapilkalra04 commented
I seem to be getting this error:
![11221](https://user-images.githubusercontent.com/35236159/34903388-64052584-f856-11e7-956a-234fa4d4d886.png)

2018-01-20 06:53 UTC, raghavagrawal commented
I have done changes. Installation still has issues when institute's internet.

2018-01-20 09:28 UTC, prasadtalasila requested changes

2018-01-20 09:28 UTC, prasadtalasila commented on scripts/install.sh
> +sudo bash scripts/java_install.sh
check for JAVA environment and bail out if it does not exist.

2018-01-23 15:12 UTC, raghavagrawal commented
@prasadtalasila I have added the check for tomcat installation.

2018-01-28 09:33 UTC, prasadtalasila requested changes

2018-01-28 09:33 UTC, prasadtalasila commented on scripts/install.sh
> +export M2_HOME=/opt/maven
@raghavagrawal These exports are going to be effective only during the vagrant box installation. They will not be available for vagrant user after vagrant ssh login.

You need to put these exports of environment variables in `/home/vagrant/.bashrc` file. An example would be as follows.

echo 'export M2=$M2_HOME/bin' >> /home/vagrant/.bashrc

2018-01-28 09:52 UTC, prasadtalasila commented
The changes look good to me. Since this is an installation PR, two people need to install, use and certify the installation. @kapilkalra04 and @ParvDani07 can do that.

2018-01-29 15:07 UTC, merged

2018-01-30 15:09 UTC, parv commented
I don't know why I was mentioned earlier (unless I stumbled here in slumber). Would you please not mention me here? Thanks much.