update install scripts
prasadtalasila/BITS-Darshini pull request #164
Opened 2018-01-30 07:09 UTC by prasadtalasila

Updates the install scripts with the following improvements.

* Tomcat 8.5 installation with the URL coming from Apache EU mirror
* Updates node.js to 8.9x
* Removes errors in the tomcat.service file
* Improves the code in install.sh shell script

@raghavagrawal please review the changes proposed here.

2018-01-30 09:36 UTC, prasadtalasila commented
@adityaketkar can you see any reason for the reduction in code coverage in this PR?

2018-01-30 13:51 UTC, adityaketkar commented
@prasadtalasila  The coverage drop is in IPv4Analyzer.java, which we have patched on dev branch.
The changes that prevent this are not included in tomcat8 branch.

2018-01-31 10:17 UTC, prasadtalasila commented
@adityaketkar I rebased the tomcat8 branch with the dev branch. Now the codecov is showing a correct report. Please verify the same.

2018-01-31 17:18 UTC, raghavagrawal requested changes
@prasadtalasila I have added a few comments for your approval

2018-01-31 17:18 UTC, raghavagrawal commented on scripts/install.sh
> +npm install --prefix src/main/webapp/WEB-INF
@prasadtalasila I was facing problems in installation when using --prefix. I request you see this issue.
[https://github.com/npm/npm/issues/9901](url)

2018-01-31 17:18 UTC, raghavagrawal commented on scripts/install.sh
> +sudo tar xzf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
@prasadtalasila We will have to make /opt/tomcat directory.

2018-01-31 17:18 UTC, raghavagrawal commented on scripts/install.sh
> +sudo mkdir -p /opt/darshini-es/data
@prasadtalasila Will these 'sudo' be required as we will be running the scripts as superuser.

2018-01-31 17:54 UTC, prasadtalasila commented on scripts/install.sh
> +sudo mkdir -p /opt/darshini-es/data
We could do it either way. I thought that running the script as regular user, but giving sudo to the required commands would be better from security point of view.

2018-01-31 17:54 UTC, prasadtalasila commented on scripts/install.sh
> +sudo mkdir -p /opt/darshini-es/data
Also the [install](https://github.com/prasadtalasila/BITS-Darshini/wiki/Install) document has been updated accordingly.

2018-01-31 17:58 UTC, prasadtalasila commented
@raghavagrawal one unaddressed issue is the use of `--prefix`. You said that you were facing problems. Can you please elaborate on the problems and give a log?

2018-02-01 04:57 UTC, merged